SCHEDULE_SITUATION_CANCEL = 4
SCHEDULE_SITUATION_SCHEDULED = 1
SCHEDULE_ORIGIN_CANCEL = 1
PAYMENT_CONDITION_COURTESY = 4
PLAN_PROMO = 7
SUBSCRIPTION_STATUS_ACTIVE = 3
SUBSCRIPTION_STATUS_CANCELED_BY_CLIENT = 11
SUBSCRIPTION_STATUS_CANCELED_BY_NON_PAYMENT = 12
